name: Ci

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '25'
    - name: Flutter action
      uses: subosito/flutter-action@v2.23.0
    - name: Setup Python
      uses: actions/setup-python@v7.0.0
    - name: Set target for rust
      run: |
        rustup target add aarch64-linux-android
        rustup target add x86_64-linux-android
    - name: Install system deps
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
    - name: Setup Android NDK
      id: ndk
      uses: nttld/setup-ndk@v1.6.0
      with: 
        ndk-version: r27d
    - name: Check Rust
      env:
        ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
      run: |
        cd native
        cargo check
    - name: Prebuild
      env:
        ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
      run: python3 pre_build.py
    - name: Flutter check
      run: |
        dart format . --set-exit-if-changed
        flutter analyze
    - name: Generate key
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "${{ secrets.KEY_STORE }}" | base64 --decode > android/app/key.jks  && echo "${{ secrets.KEY_PROPERTIES }}" > android/app/key.properties
    - name: Flutter build
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        flutter build apk --build-name="${GITHUB_REF_NAME#v}" --build-number="$GITHUB_RUN_NUMBER" -PuseReleaseSigning=true
        flutter build apk --split-per-abi --build-name="${GITHUB_REF_NAME#v}" --build-number="$GITHUB_RUN_NUMBER" -PuseReleaseSigning=true
    - name: Rename apk
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_armeabi-v7a.apk
        mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_arm64-v8a.apk
        mv build/app/outputs/flutter-apk/app-x86_64-release.apk  build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_x86_64.apk
        mv build/app/outputs/flutter-apk/app-release.apk  build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_universal.apk
    - name: GH Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v3.0.2
      with:
          token: ${{ secrets.TOKEN }}
          files: |
            build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_armeabi-v7a.apk
            build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_arm64-v8a.apk
            build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_x86_64.apk
            build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_universal.apk
    - name: Gitee Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
          sudo apt install python3-requests
          python3 release_to_gitee.py --token ${{ secrets.GITEE_TOKEN}} --tag ${{github.ref_name}} --server ${{ secrets.PROXY_SERVER }} --psw ${{ secrets.PSW }} --file build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_armeabi-v7a.apk
          python3 release_to_gitee.py --token ${{ secrets.GITEE_TOKEN}} --tag ${{github.ref_name}} --server ${{ secrets.PROXY_SERVER }} --psw ${{ secrets.PSW }} --file build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_arm64-v8a.apk
          python3 release_to_gitee.py --token ${{ secrets.GITEE_TOKEN}} --tag ${{github.ref_name}} --server ${{ secrets.PROXY_SERVER }} --psw ${{ secrets.PSW }} --file build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_x86_64.apk
          python3 release_to_gitee.py --token ${{ secrets.GITEE_TOKEN}} --tag ${{github.ref_name}} --server ${{ secrets.PROXY_SERVER }} --psw ${{ secrets.PSW }} --file build/app/outputs/flutter-apk/Nek0_${{github.ref_name}}_android_universal.apk
      
